### ISSUE TITLE
Tile selection doesn't dissapear

### ISSUE THREAD

**Issue by SinonLynx** [MagnonGames/DTile#12]
When turning off the tile selection tool, the tiles previously selected while using the tile selection tool still stay selected.
![image](https://cloud.githubusercontent.com/assets/18260167/19931910/7751e604-a10e-11e6-8301-03e7245bf59b.png)
![image](https://cloud.githubusercontent.com/assets/18260167/19931922/812aa35a-a10e-11e6-8cd6-b7b4e38c6aad.png)

**Comment by dotellie** [comment]
This is partially intentional since this should be a tool. The "enable selection" text is kind of misleading that way. I do get what you mean though and I agree that there should definitely be a way to "deselect".
