### ISSUE TITLE
Map loading indicator positional issue

### ISSUE THREAD

**Issue by SinonLynx** [MagnonGames/DTile#13]
When loading in a new map, the indicator that shows that DTile is loading the map ends up on the row below the Import map button, rather than on the same row.
![image](https://cloud.githubusercontent.com/assets/18260167/19932332/021cf6b0-a110-11e6-92c2-5df49e7256fb.png)

**Comment by dotellie** [comment]
This is **SUPER** temporary. I was just testing around really. We need to have a proper map importing dialog in the future anyway, so that's gonna disappear before you know it pretty much.
