### ISSUE TITLE
Importing high resulotion pictures as tilesets

### ISSUE THREAD

**Issue by Kjellmer** [MagnonGames/DTile#16]
When you impost a high resoulotion picture as a tilemap the picture gets disoriented
![skarmklipp](https://cloud.githubusercontent.com/assets/19638206/21619856/de63652a-d1f1-11e6-8d5c-c1a7880f33ac.PNG)

**Comment by dotellie** [comment]
What are the dimensions of the "tileset" you used and what tile sizes do you have set on your map?

**Comment by Kjellmer** [comment]
Tileset 520 x 320 
Tilemap 50 x 50

**Comment by dotellie** [comment]
Not tile tilemap size, the tile size.

**Comment by Kjellmer** [comment]
16 x 16

**Comment by dotellie** [comment]
I'll take a look at it.

**Comment by dotellie** [comment]
@CurryNRice Is it possible you could try this on the rewritten version to see if it's still a problem?
