### ISSUE TITLE
Scroll Creates huge black bar

### ISSUE THREAD

**Issue by Kjellmer** [MagnonGames/DTile#25]
When you scroll down your layers and tileset it creates a black bar witch has no use.

**Comment by dotellie** [comment]
Is it possible to get a screenshot of this? I think I know what you're referring to, but just to be sure...

**Comment by Kjellmer** [comment]
![skarmklipp](https://user-images.githubusercontent.com/19638206/32549375-800c681a-c489-11e7-9f5e-8815301dc0d5.PNG)

**Comment by dotellie** [comment]
Ah, okay. I see now. I'll take a look.
