### ISSUE TITLE
All tilemaps reamain in all prodjects 

### ISSUE THREAD

**Issue by Kjellmer** [MagnonGames/DTile#26]
Even if you create a new project all old tilemaps will be crated with the same name in this project. Thogh they are empty with only layers remaining 
![skarmklipp](https://user-images.githubusercontent.com/19638206/32549467-de292384-c489-11e7-9ac0-fdca8f52be3d.PNG)
Marked in blue does are not supposed to be in that project

**Comment by dotellie** [comment]
I'll take a look. This might be simpler than it seems. It should be noted that I usually don't test with multiple projects, so that's probably why I missed this.

**Comment by dotellie** [comment]
Fixed in 15a65b1 (upcoming)
